export enum TYPOGRAPHY_VARIANT {
  DisplayOne = 'display-1',
  DisplayTwo = 'display-2',
  HeadingOne = 'heading-1',
  HeadingTwo = 'heading-2',
  HeadingTwoMedium = 'heading-2-medium',
  HeadingThree = 'heading-3',
  HeadingThreeMedium = 'heading-3-medium',
  HeadingRegular = 'heading-regular',
  HeadingSubtitle = 'heading-subtitle',
  HeadingSubtitleMedium = 'heading-subtitle-medium',
  HeadingSmall = 'heading-small',
  BodyBig = 'body-big',
  BodyNormal = 'body-normal',
  BodySmall = 'body-small',
  BodyParagraph = 'body-paragraph',
  AllCaptions = 'all-captions',
  Caption = 'caption',
}
